version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "movies"
    ports:
      - "5432:5432"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    image: halo-lab-test
    depends_on:
      - postgres
      - redis
    ports: 
      - "3000:3000"
    volumes:
      - ./src:/usr/app/src